Add client pipeline using gh-actions.
- Change alpha -> staging.
- Add cfn for client.

diff --git a/copilot/buildspec.yml b/copilot/buildspec.yml
--- a/copilot/buildspec.yml
+++ b/copilot/buildspec.yml
@@ -26,18 +26,24 @@ phases:
       - printenv DOCKERHUB_TOKEN | docker login --username ${DOCKERHUB_USERNAME} --password-stdin
 
   build:
-    commands:
-      - echo "Cloning server & client"
+    commands:  # Custom
+      - echo "Cloning server"
       - export SUB_MODULES_DEP_FILE=./sub-modules-dep.json
+      - export DEEP_SERVER_DEPLOY=`jq -r '.server.deploy' ${SUB_MODULES_DEP_FILE}`
       - export DEEP_SERVER_REPO=`jq -r '.server.repo' ${SUB_MODULES_DEP_FILE}`
       - export DEEP_SERVER_BRANCH=`jq -r '.server.branch' ${SUB_MODULES_DEP_FILE}`
-      # - export DEEP_CLIENT_REPO=`jq -r '.server.repo' ${SUB_MODULES_DEP_FILE}`
-      # - export DEEP_CLIENT_BRANCH=`jq -r '.server.branch' ${SUB_MODULES_DEP_FILE}`
+      - >
+        if ! [ "${DEEP_SERVER_DEPLOY,,}" = "true" ]; then
+          echo 'No deployment required!!';
+          aws codebuild stop-build --id ${CODEBUILD_BUILD_ID}
+          exit 0;
+        fi
       - git clone --depth 1 --branch=${DEEP_SERVER_BRANCH} ${DEEP_SERVER_REPO} ./server
-      # - git clone --depth 1 --branch=${DEEP_CLIENT_BRANCH} ${DEEP_CLIENT_REPO} ./client
-      - echo "[Server] Building server worker image"
-      - aws ecr get-login-password --region $region | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$region.amazonaws.com
+      # Server
       - export DOCKER_IMAGE_SERVER=$AWS_ACCOUNT_ID.dkr.ecr.$region.amazonaws.com/deep/worker:builder
+      - export DOCKER_IMAGE_SERVER_DOMAIN=$(echo $DOCKER_IMAGE_SERVER | cut -d '/' -f 1)
+      - echo "[Server] Building server worker image"
+      - aws ecr get-login-password --region $region | docker login --username AWS --password-stdin $DOCKER_IMAGE_SERVER_DOMAIN
       - docker pull $DOCKER_IMAGE_SERVER || true
       - docker build -t $DOCKER_IMAGE_SERVER --cache-from $DOCKER_IMAGE_SERVER ./server
       - echo "[Server] Running tests"
@@ -56,7 +62,7 @@ phases:
           }
       - docker-compose -f ./server/gh-docker-compose.yml run --rm server /code/scripts/run_tests.sh
       - echo "[Server] Pushing builder image"
-      - aws ecr get-login-password --region $region | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$region.amazonaws.com
+      - aws ecr get-login-password --region $region | docker login --username AWS --password-stdin $DOCKER_IMAGE_SERVER_DOMAIN
       - docker push $DOCKER_IMAGE_SERVER
 
   post_build:
